INSERT INTO products (name, description, price, image_url) VALUES
('Wireless Headphones', 'Premium sound quality with noise cancellation', 99.99, '/images/headphones.svg'),
('Smart Watch', 'Track your health and stay connected', 149.99, '/images/watch.svg'),
('Bluetooth Speaker', 'Portable speaker with rich bass', 59.99, '/images/speaker.svg'),
('Ultrabook Laptop', 'Lightweight laptop for work and play', 899.99, '/images/laptop.svg'),
('Digital Camera', 'Capture every moment in stunning detail', 449.99, '/images/camera.svg'),
('Android Tablet', 'Perfect for entertainment and productivity', 329.99, '/images/tablet.svg'),
('USB-C Cable', 'Fast charging data cable', 14.99, '/images/usb-cable.svg'),
('Wireless Earbuds', 'Compact true-wireless earbuds', 79.99, '/images/earbuds.svg'),
('4K Webcam', 'Crystal-clear video for streaming', 129.99, '/images/webcam.svg'),
('Rechargeable Power Bank', '20000mAh portable charger', 39.99, '/images/powerbank.svg'),
('Smart Speaker', 'Portable Bluetooth speaker with voice assistant', 124.99, '/images/speaker.svg'),
('Laptop Backpack', 'Waterproof 15-inch laptop carrier', 49.99, '/images/backpack.svg'),
('Wireless Charger Pad', 'Qi-compatible charging pad', 29.99, '/images/charger.svg'),
('Bluetooth Mouse', 'Ergonomic wireless mouse', 39.95, '/images/mouse.svg'),
('Gaming Keyboard', 'Mechanical keyboard with RGB lighting', 89.99, '/images/keyboard.svg'),
('Mouse Pad', 'Non-slip gaming mouse pad', 19.99, '/images/mousepad.svg'),
('HDMI Cable', 'High-speed 4K HDMI cable', 24.99, '/images/hdmi.svg'),
('External SSD', '1TB portable solid-state drive', 129.99, '/images/ssd.svg'),
('Laptop Stand', 'Adjustable aluminum laptop stand', 34.99, '/images/stand.svg'),
('Phone Tripod', 'Flexible tripod for smartphones', 25.99, '/images/tripod.svg');